Stm32 g4 variant
ABOSTM/Arduino_Core_STM32 pull request #4
Opened 2021-02-18 18:12 UTC by ABOSTM

**Summary**

Stm32 g4 variant

2021-02-19 07:52 UTC, ABOSTM commented
@fpistm Review requested for last commit:
    [variant] Add Generic G4 and Nucleo G4

2021-02-19 09:53 UTC, fpistm requested changes

2021-02-19 09:53 UTC, fpistm commented on README.md
> +| :yellow_heart: | STM32G474RE | Generic Board | **2.0.0** |  |
The generic provide also support of STM32G474RB and STM32G474RC

2021-02-19 09:53 UTC, fpistm commented on README.md
> +| :yellow_heart: | STM32G431RB | Generic Board | **2.0.0** |  |
Ditto 6 and 8

2021-02-19 09:53 UTC, fpistm commented on README.md
> +| :yellow_heart: | STM32G431KB | Generic Board | **2.0.0** |  |
ditto 6 and 8

2021-02-19 09:53 UTC, fpistm commented on boards.txt
> +Nucleo_64.menu.pnum.NUCLEO_G431RB.build.variant=STM32G4xx/Generic_G431RB
Generic_G431Rx

2021-02-19 09:53 UTC, fpistm commented on boards.txt
> +Nucleo_64.menu.pnum.NUCLEO_G474RE.build.variant=STM32G4xx/Generic_G474RE
Generic_G474Rx

2021-02-19 09:53 UTC, fpistm commented on boards.txt
> +Nucleo_32.menu.pnum.NUCLEO_G431KB.build.variant=STM32G4xx/Generic_G431KB
Generic_G431Kx

2021-02-19 09:53 UTC, fpistm commented on boards.txt
> +GenG4.menu.pnum.GENERIC_G474RE.build.variant=STM32G4xx/Generic_G474RE
It misses some generic variant for each G4

2021-02-19 09:53 UTC, fpistm commented on boards.txt
> +
??

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431KB/variant.cpp
> +#if defined(ARDUINO_GENERIC_G431KB)
#if defined(ARDUINO_GENERIC_G431K6)  || defined(ARDUINO_GENERIC_G431K8)  || defined(ARDUINO_GENERIC_G431KB)

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431KB/variant.cpp
> +
to remove

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431KB/variant.h
> +#if !defined(ARDUINO_GENERIC_G431KB)
Ditto missing some defined

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431KB/variant_NUCLEO_G431KB.cpp
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431KB/variant_NUCLEO_G431KB.h
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431RB/variant.cpp
> +#if defined(ARDUINO_GENERIC_G431RB)
ditto

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431RB/variant.cpp
> +   * HSE_VALUE defined in the stm32g0xx_hal_conf_default.h is used.
stm32g4xx_hal_conf_default.h

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431RB/variant.h
> +#if !defined(ARDUINO_GENERIC_G431RB)
ditto

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431RB/variant_NUCLEO_G431RB.cpp
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G431RB/variant_NUCLEO_G431RB.h
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G474RE/variant.cpp
> +#if defined(ARDUINO_GENERIC_G474RE)
ditto

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G474RE/variant.h
> +#if !defined(ARDUINO_GENERIC_G474RE)
ditto

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G474RE/variant_NUCLEO_G474RE.cpp
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-02-19 09:53 UTC, fpistm commented on variants/STM32G4xx/Generic_G474RE/variant_NUCLEO_G474RE.h
> + * Copyright (c) 2021, STMicroelectronics
2019-2021

2021-03-11 07:55 UTC, ABOSTM commented
@fpistm ,
Rebase on latest automatic generic variant generation.
Fixes CI issue (Astyle + compilation issue)
Take your remarks into account

2021-09-20 15:13 UTC, ABOSTM commented
ABOSTM fork. Close this PR

2021-09-20 15:13 UTC, closed without merging